# Configuration for pipeline using TPCH

# File path where pipelines are stored
pipelines: /home/amemory/Data/prdbsens/pipelines/

name: tpch                     # This pipeline

# CSV files for each CRIME relation
relations_orig: rel                 
# relations: rel                 
# relations: rel/sam/50000
relations: rel/sam/20000

relation_sampling:              # Relations larger than this will be sampled
  # max_rows: 50000
  max_rows: 20000               # Full region, nation and supplier

# Kinds of transformations
transform:
  pow:                          # Tuple confidence
    exponents: pow/exponents.csv
    1st:                        # Transform the first relation
      dir: pow/1st
    all:                        # Transform all relations
      dir: pow/all

# A blank Trio DB on localhost
# See scripts/setup_scratch_database.sh
database:
  name: trio1
  user: amemory
  password: password

